Resources:
  privateNatGateway2:
    DependsOn: attachGateway
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - EIP2
          - AllocationId
      SubnetId: !Ref publicSubnet2

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc