Resources:
  privateNatGateway2:
    DependsOn: attachGateway1
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - EIP2
          - AllocationId
      SubnetId: !Ref publicSubnet2