Resources:
  k8sInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - k8s

  master:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref privateSubnet1
      InstanceType: !Ref InstanceTypeParameter
      ImageId: "ami-0c6b1d09930fac512"
      KeyName: !Ref keynameParameter
      IamInstanceProfile: !Ref k8sInstanceProfile
      SecurityGroupIds:
        - !Ref privateSubnet1SecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource bastion --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource bastion --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: Master
        - Key: kubernetes.io/cluster/k8s.melkouhen.net
          Value: owned

  nodes:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: !Ref master
      MinSize: !Ref k8sMinNodeSizeParameter
      MaxSize: !Ref k8sMaxNodeSizeParameter
      VPCZoneIdentifier: [!Ref privateSubnet1]
      Tags:
        - Key: Name
          Value: Node
          PropagateAtLaunch: true
        - Key: kubernetes.io/cluster/k8s.melkouhen.net
          Value: owned
          PropagateAtLaunch: true