Resources:
  master:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref privateSubnet
      InstanceType: !Ref InstanceTypeParameter
      ImageId: "ami-0c6b1d09930fac512"
      KeyName: !Ref keynameParameter
      SecurityGroupIds:
        - !Ref privateSubnetSecurityGroup
      Tags:
        - Key: Type
          Value: Master
  nodes:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: !Ref master
      MinSize: !Ref k8sMinNodeSizeParameter
      MaxSize: !Ref k8sMaxNodeSizeParameter
      VPCZoneIdentifier: [!Ref privateSubnet]
      Tags:
        - Key: Type
          Value: Node
          PropagateAtLaunch: true