Resources:
  InstanceProfile:
    Type : AWS::IAM::InstanceProfile
    Properties:
      Path : "/"
      Roles :
        - k8s

  master:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref privateSubnet
      InstanceType: !Ref InstanceTypeParameter
      ImageId: "ami-0c6b1d09930fac512"
      KeyName: !Ref keynameParameter
      IamInstanceProfile : !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref privateSubnetSecurityGroup
      Tags:
        - Key: Name
          Value: Master
        - Key: kubernetes.io/cluster/k8.test.ippon.com
          Value: owned
  nodes:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      InstanceId: !Ref master
      MinSize: !Ref k8sMinNodeSizeParameter
      MaxSize: !Ref k8sMaxNodeSizeParameter
      VPCZoneIdentifier: [!Ref privateSubnet]
      Tags:
        - Key: Name
          Value: Node
          PropagateAtLaunch: true
        - Key: kubernetes.io/cluster/k8.test.ippon.com
          Value: owned
          PropagateAtLaunch: true