Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  VPCCidrParameter:
    Type: String
    Default: "10.0.0.0/16"
    Description: VPC CIDR
  privateSubnetCidrParameter:
    Type: String
    Default: "10.0.1.0/24"
    Description: Private Subnet CIDR
  publicSubnetCidrParameter:
    Type: String
    Default: "10.0.0.0/24"
    Description: Public Subnet CIDR
  keynameParameter:
    Type: String
    Default: MyKeyPair
    Description: Keyname
  k8sNodeSizeParameter:
    Type: number
    Default: 1
    Description: Number Of Nodes