Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3a.medium
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  VPCCidrParameter:
    Type: String
    Default: "10.0.0.0/16"
    Description: VPC CIDR
  privateSubnet1CidrParameter:
    Type: String
    Default: "10.0.2.0/24"
    Description: Private Subnet CIDR
  privateSubnet2CidrParameter:
    Type: String
    Default: "10.0.3.0/24"
    Description: Private Subnet CIDR
  publicSubnet1CidrParameter:
    Type: String
    Default: "10.0.0.0/24"
    Description: Public Subnet CIDR
  publicSubnet2CidrParameter:
    Type: String
    Default: "10.0.1.0/24"
    Description: Public Subnet CIDR
  keynameParameter:
    Type: String
    Default: MyKeyPair
    Description: Keyname
  k8sMinNodeSizeParameter:
    Type: Number
    Default: "0"
    Description: Number Of Nodes
  k8sMaxNodeSizeParameter:
    Type: Number
    Default: "1"
    Description: Number Of Nodes