Resources:
  privateSubnet2NatGateway:
    DependsOn: attachGateway
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - privateSubnet2EIP
          - AllocationId
      SubnetId: !Ref publicSubnet2

  privateSubnet2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc