Resources:
  privateNatGateway1:
    DependsOn: attachGateway1
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId
      SubnetId: !Ref publicSubnet1
  privateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  privateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref privateRouteTable1
      SubnetId: !Ref privateSubnet1
  privateNatRoute1:
    Type: AWS::EC2::Route
    DependsOn:
      - privateNatGateway1
    Properties:
      RouteTableId: !Ref privateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref privateNatGateway1
  privateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref privateSubnet1CidrParameter
      VpcId: !Ref VPC
      Tags:
        - Key: kubernetes.io/cluster/k8s.melkouhen.net
          Value: owned
  privateSubnet1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: privateSubnet1SecurityGroup
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"