Resources:
  publicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref publicSubnet2CidrParameter
      VpcId: !Ref VPC
      AvailabilityZone: us-east-1e
      Tags:
        - Key: kubernetes.io/cluster/k8s.melkouhen.net
          Value: owned
  publicSubnet2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: publicSubnet2SecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"