Resources:
  publicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref publicSubnet1RouteTable
      SubnetId: !Ref publicSubnet1
  publicSubnet1Route:
    Type: AWS::EC2::Route
    DependsOn:
      - internetGateway
      - attachGateway
    Properties:
      RouteTableId: !Ref publicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGateway
  publicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref publicSubnet1CidrParameter
      VpcId: !Ref VPC
      AvailabilityZone: us-east-1d
      Tags:
        - Key: kubernetes.io/cluster/k8s.melkouhen.net
          Value: owned
  publicSubnet1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: publicSubnet1SecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"